services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: AdaptEd
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - '3307:3306'
